name: Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Tag Name
        id: tagName
        uses: olegtarasov/get-tag@v2.1.1
      - name: Format Tag Name
        id: formattedTag
        env:
          TAG_NAME: ${{ steps.tagName.outputs.tag }}
        run: |
          echo "::set-output name=tag::${TAG_NAME#v}"
      - name: Build Release
        uses: ./
        with:
          version-name: ${{ steps.formattedTag.outputs.tag }}
      - name: Release Result
        env:
          TITLE: ${{ steps.release.outputs.title }}
          RELEASE: ${{ steps.release.outputs.body }}
        run: |
          printf "$TITLE\n\n"
          printf "%s\n" "$RELEASE"
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ steps.tagName.outputs.tag }}
          name: ${{ steps.release.outputs.title }}
          body: ${{ steps.release.outputs.body }}