name: Release

on:
  push:
    tags:
      - "*.*.*"
  workflow_dispatch:

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Get Tag Name
        id: tagName
        uses: olegtarasov/get-tag@v2.1.1
      - name: Build Release
        id: release
        uses: MatteoCampinoti94/changelog-to-release@main
        with:
          version-name: ${{ steps.tagName.outputs.tag }}
      - name: Build Release File
        env:
          TAG: ${{ steps.tagName.outputs.tag }}
          RELEASE: ${{ steps.release.outputs.body }}
        run: |
          touch RELEASE.md
          printf "%s" "$RELEASE" > RELEASE.md
          printf "\n\n## 🚚 Distribution" >> RELEASE.md
          printf "\n\n[changelog-to-release@%s](https://github.com/marketplace/actions/changelog-to-release?version=%s)" "$TAG" "$TAG" >> RELEASE.md
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ steps.tagName.outputs.tag }}
          name: ${{ steps.release.outputs.title }}
          body_path: RELEASE.md