name: Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get Tag Name
        id: tag
        run: |
          TAG="$(git tag -l --sort=-version:refname | head -1)"
          echo $TAG
          echo "::set-output name=tag::$TAG"
          echo "::set-output name=tagName::${TAG#v}"
      - name: Build Release
        uses: ./
        with:
          version-name: ${{ steps.tag.outputs.tagName }}
      - name: Release Result
        env:
          TITLE: ${{ steps.release.outputs.title }}
          RELEASE: ${{ steps.release.outputs.body }}
        run: |
          printf "$TITLE\n\n"
          printf "%s\n" "$RELEASE"
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ steps.tag.outputs.tag }}
          name: ${{ steps.release.outputs.title }}
          body: ${{ steps.release.outputs.body }}