name: Test

on:
  push:


jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v5
        with:
          node-version: 24
      - run: npm install
      - name: Build .env file
        run: |
          touch .env.test
          printf 'INPUT_version-name="v1.0.0"\n' >> .env.test
          printf 'INPUT_changelog="CHANGELOG.md"\n' >> .env.test
      - name: Test action
        run: npm run test
